### ISSUE TITLE
Feature - split nginx conf files into smaller chunks

### ISSUE THREAD

**Issue by rakibabu** [aliuosio/mage2.docker#10]
Hi @aliuosio ,

Thanks for sharing this awesome docker build. I saw a huge chunk of locations in the nginx default.conf. Can we split this into smaller chunks so we can manage updates in the magento nginx file? 

I propose a structure Serverpilot has:

```
include /etc/nginx/conf/[subdir]*.nonssl_conf;
include /etc/nginx/conf/[subdir]/*.conf;
```

This way we can make multiple files:
- Nginx pagespeed
- SSL
- Default Magento Nginx
- Cloudflare conf 
- etc.....

Happy to hear your thoughts on this.

Raki

**Comment by aliuosio** [comment]
yes you can...
create a fork of this repository on Github and send me a pull request.
i like the idea

**Comment by rakibabu** [comment]
Nice i'll send you the PR :)

**Comment by aliuosio** [comment]
Thumbs up... thx

**Comment by rakibabu** [comment]
The PR is almost done :)
