### ISSUE TITLE
Bug - gem install docker-sync without root permissions

### ISSUE THREAD

**Issue by rakibabu** [aliuosio/mage2.docker#13]
Hi,

The setup script breaks on gem install docker-sync on mac osx. 

<img width="571" alt="Screenshot 2019-12-15 at 13 54 50" src="https://user-images.githubusercontent.com/14089150/70862997-8867df00-1f43-11ea-80ec-e9990b77896c.png">

According the docs the can install docker sync with root permissions or with user permissions. I'll make a PR for this.

https://docker-sync.readthedocs.io/en/latest/getting-started/installation.html

Regards,

**Comment by aliuosio** [comment]
@rakibabu 
`gem install --user-install docker-sync;
WARNING:  You don't have /Users/krusty/.gem/ruby/2.6.0/bin in your PATH,
	  gem executables will not run.`

i get this warning...
do you have a handy script which could had the path automatically after 
`gem install --user-install docker-sync`

**Comment by aliuosio** [comment]
@rakibabu 
get the latest sources git fetch && git pull

**Comment by rakibabu** [comment]
Hi @aliuosio ,

It was already fixed within the PR right? Don't get your comment.

**Comment by aliuosio** [comment]
`gem install docker-sync` is now installed using sudo.
since you set the guid and userid to 1000
