### ISSUE TITLE
Install issue.

### ISSUE THREAD

**Issue by trianhhuynh** [aliuosio/mage2.docker#21]
**Describe the bug**

`Successfully installed docker-sync-0.5.14
Parsing documentation for docker-sync-0.5.14
Done installing documentation for docker-sync after 0 seconds
1 gem installed
source ~/.bash_profile`

I'm using OSX. It always logout after the above step.

**Comment by aliuosio** [comment]
@trianhhuynh 
have you tried open a new terminal tab to run ./install.sh again?
It take time to sync the volume on OSX.

**Comment by trianhhuynh** [comment]
I have removed the path` if which ruby >/dev/null && which gem >/dev/null; then
            PATH="$(ruby -r rubygems -e 'puts Gem.user_dir')/bin:$PATH"
            if [ -f ~/.bash_profile ]; then
                echo "source ~/.bash_profile";
                source ~/.bash_profile

                echo "source ~/.profile";
                source ~/.profile

                echo "source ~/.bashrc";
                source ~/.bashrc
            fi
        fi`

and it works like a charm.

**Comment by aliuosio** [comment]
@trianhhuynh 
Sounds familiar :smile:  :+1:
Please create a new fork of this repo and send me a pull request. 
Just delete your fork and create it again to have the newest version

Can you do that?

**Comment by trianhhuynh** [comment]
Hi @aliuosio ,
Sure. I will.

**Comment by aliuosio** [comment]
fixed after next mere into master branch
