### ISSUE TITLE
SQLSTATE[HY000] [2006] MySQL server has gone away  In InstallCommand.php line 264:    Parameter validation failed

### ISSUE THREAD

**Issue by hermersnana** [aliuosio/mage2.docker#22]
**Describe the bug**
SQLSTATE[HY000] [2006] MySQL server has gone away

In InstallCommand.php line 264:

  Parameter validation failed
can not connect the MySQL. see the error info 

**To Reproduce**
1. i used the ./install.sh 
2. by the mangeto install ,i got the error as above. i try change the Host name to localhost or mysql ,or container name from sql,but it not work.

thanks

best regards
lee

**Comment by aliuosio** [comment]
@hermersnana 
This is a Problem since the DB was changed from MySQL to MariaDB.
I used to have a config for MySQL. I will implement this again with MariaDB.

Try this:
1. start the the Stack with `docker-compose up -d`
2. comment out `dockerRefresh` with `# dockerRefresh` in install.sh
3. run `./install.sh` again

Please give me a feedback as soon as you have tried this.

**Comment by hermersnana** [comment]
hallo,
i have tried, but i got the error, i have checked ,

php_7.3  Cannot create container for service php: failed to mount local volume: mount /htdocs:/var/lib/docker/volumes/mage2_app_data/_data, flags: 0x1000: no such file or directory

ERROR: for php  Cannot create container for service php: failed to mount local volume: mount /htdocs:/var/lib/docker/volumes/mage2_app_data/_data, flags: 0x1000: no such file or directory
ERROR: Encountered errors while bringing up the project.

thanks.

**Comment by aliuosio** [comment]
@hermersnana 
Try this:

1. start the the Stack with `docker-compose down -v`
2. start the the Stack with `docker-compose up -d`
3. comment out `dockerRefresh` with `# dockerRefresh` in install.sh
4. run `./install.sh` again

Please give me a feedback as soon as you have tried this.

**Comment by hermersnana** [comment]
Hi 

Thanks, i have tried, i have same error 

ERROR: for nanamarkt_php_7.3  Cannot create container for service php: failed to mount local volume: mount /htdocs:/var/lib/docker/volumes/nanamarkt_app_data/_data, flags: 0x1000: no such file or directory

 

ERROR: for php  Cannot create container for service php: failed to mount local volume: mount /htdocs:/var/lib/docker/volumes/nanamarkt_app_data/_data, flags: 0x1000: no such file or directory

ERROR: Encountered errors while bringing up the project.

 

Ip ,35.158.238.111

Key.

Can you try it, it just test server ,if  you want.

 

Thank you 

 

Best regards

lee

 

Von: Osiozekhai Aliu <notifications@github.com>
Antworten an: "aliuosio/mage2.docker" <reply@reply.github.com>
Datum: Donnerstag, 9. April 2020 um 10:59
An: "aliuosio/mage2.docker" <mage2.docker@noreply.github.com>
Cc: hermersnana <hermers.gmbh@googlemail.com>, Mention <mention@noreply.github.com>
Betreff: Re: [aliuosio/mage2.docker] SQLSTATE[HY000] [2006] MySQL server has gone away In InstallCommand.php line 264: Parameter validation failed (#22)

 

@hermersnana
Try this:
start the the Stack with docker-compose down -v
start the the Stack with docker-compose up -d
comment out dockerRefresh with # dockerRefresh in install.sh
run ./install.sh again
Please give me a feedback as soon as you have tried this.

**Comment by aliuosio** [comment]
@hermersnana
Do you have the folder `htdcos`?

**Comment by hermersnana** [comment]
Yes ，it is in /www/wwwroot/nanamarkt/htdocs

 

Von: Osiozekhai Aliu <notifications@github.com>
Antworten an: "aliuosio/mage2.docker" <reply@reply.github.com>
Datum: Donnerstag, 9. April 2020 um 12:08
An: "aliuosio/mage2.docker" <mage2.docker@noreply.github.com>
Cc: hermersnana <hermers.gmbh@googlemail.com>, Mention <mention@noreply.github.com>
Betreff: Re: [aliuosio/mage2.docker] SQLSTATE[HY000] [2006] MySQL server has gone away In InstallCommand.php line 264: Parameter validation failed (#22)

 

@hermersnana
Do you have the folder htdcos?

**Comment by aliuosio** [comment]
@hermersnana 
the folder `htdocs` has to be in the clone of this project

**Comment by hermersnana** [comment]
Yes, it from the clone of the project

 

Von: Osiozekhai Aliu <notifications@github.com>
Antworten an: "aliuosio/mage2.docker" <reply@reply.github.com>
Datum: Donnerstag, 9. April 2020 um 12:17
An: "aliuosio/mage2.docker" <mage2.docker@noreply.github.com>
Cc: hermersnana <hermers.gmbh@googlemail.com>, Mention <mention@noreply.github.com>
Betreff: Re: [aliuosio/mage2.docker] SQLSTATE[HY000] [2006] MySQL server has gone away In InstallCommand.php line 264: Parameter validation failed (#22)

 

@hermersnana
the folder htdocs has to be in the clone of this project

**Comment by aliuosio** [comment]
@hermersnana 
Maybe Solution
1. `docker-compose down -v;` # the stack is stppoed and all volumes are deleted
2. `git fetch && git pull` # get the latest sources from this project
3. `./install.sh`

**Comment by hermersnana** [comment]
it worked, thanks.

**Comment by aliuosio** [comment]
Delete and clone project again and follow the steps I mentioned before, please

**Comment by aliuosio** [comment]
@hermersnana 
please star the project and contribute if you have some improvements.
