### ISSUE TITLE
Unable to complete magento installation 

### ISSUE THREAD

**Issue by MuBoori** [aliuosio/mage2.docker#24]
**Describe the bug**
when I run this command ./install.sh 

it reaches here and it failed
[Progress: 2 / 994]
Enabling Maintenance Mode...

In Abstract.php line 144:
                                                    
  SQLSTATE[HY000] [2002] No such file or directory  
                                                    

In Abstract.php line 128:
                                                    
  SQLSTATE[HY000] [2002] No such file or directory  
                                                    
I'm using MAC 10.15.2

**Comment by aliuosio** [comment]
@MuBoori 
looking at it... has to do entrypoint script i overwrote use docker-compose on the container db.
Hope to get it done today. i will inform you

**Comment by aliuosio** [comment]
@MuBoori 
gt the newest sources for this repo ans run `./install.sh` once more

**Comment by aliuosio** [comment]
@MuBoori
Feedback? How did it go :-)

**Comment by MuBoori** [comment]
@aliuosio thanks for asking.

it works but there maybe issue when you restart
```
docker-sync start  
docker-compose -f docker-compose.osx.yml up -d;
```

also I was not able to deploy it using 
kompose up

https://kubernetes.io/docs/tasks/configure-pod-container/translate-compose-kubernetes

**Comment by aliuosio** [comment]
@MuBoori 
fork this repo and fix it please.
i believe in you ;-)

**Comment by aliuosio** [comment]
> it works but there maybe issue when you restart
@MuBoori specify please
