### ISSUE TITLE
Version is not in the correct format

### ISSUE THREAD

**Issue by JerTeske** [aliuosio/mage2.docker#25]
**Describe the bug**

**To Reproduce**
Several attempts to install, after changing quotes

**Expected behavior**
version (e.g "2.2" or "3.3")

**Screenshots**
jerteske@#:/var/lib/docker/mage2.docker$ sudo ./install.sh
.env File exists already
Absolute path to empty folder(fresh install) or running project (current: htdocs)
Domain Name (current: bizbloccenter.com)
Path to Project DB Dump or leave empty for fresh install (current: )
Which PHP 7 Version? (7.1, 7.2, 7.3) (current: 7.3)
Which MariaDB Version? (10.4.10, 10.5.2) (current: 10.4.10)
Create a login screen? (current: false)
enable Xdebug? (current: false)
Install Sample Data? (current: true)
Folder already exits
docker-compose down -v
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Docker: 1.17

**Additional context**

**Comment by aliuosio** [comment]
@JerTeske 
Both your docker-compose and docker are outdated
[Compose and Docker compatibility matrix](https://docs.docker.com/compose/compose-file/)

**latest versions**
`docker-compose -v` docker-compose version 1.25.5, build 8a1c60f6
`docker -v` Docker version 19.03.8, build afacb8b7f0

**Upgrade**
`docker-compose` https://docs.docker.com/compose/install/#install-compose
`docker` https://docs.docker.com/engine/install/debian/

**Comment by JerTeske** [comment]
jerteske@#:/var/lib/docker/mage2.docker$ sudo ./install.sh
cp ./.env.template ./.env
Absolute path to empty folder(fresh install) or running project (current: htdocs)
Domain Name (current: mage2.localhost)someuri.com
Path to Project DB Dump or leave empty for fresh install (current: )
Which PHP 7 Version? (7.1, 7.2, 7.3) (current: 7.3)
Which MariaDB Version? (10.4.10, 10.5.2) (current: 10.4.10)
Create a login screen? (current: false)
enable Xdebug? (current: false)
Install Sample Data? (current: false)true
Folder already exits
docker-compose down -v
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
jerteske@#:/var/lib/docker/mage2.docker$ docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:56 2020
 OS/Arch:           linux/amd64
 Experimental:      false


Still the case

**Comment by aliuosio** [comment]
@JerTeske 
Upgrade docker-compose. Stil outdated as the error says

`sudo curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose`

`sudo chmod +x /usr/local/bin/docker-compose`

`./install.sh`
