### ISSUE TITLE
Error ./install.sh on ubuntu

### ISSUE THREAD

**Issue by MuBoori** [aliuosio/mage2.docker#26]
ERROR: for mage2_php_7.3  Cannot create container for service php: failed to mount local volume: mount magento:/var
/lib/docker/volumes/mage2docker_app_data/_data, flags: 0x1000: no such file or directory
ERROR: for php  Cannot create container for service php: failed to mount local volume: mount magento:/var/lib/docke
r/volumes/mage2docker_app_data/_data, flags: 0x1000: no such file or directory
ERROR: Encountered errors while bringing up the project..

**Comment by aliuosio** [comment]
@MuBoori 
you have to enter an absolute path to the project folder
