### ISSUE TITLE
Install on Catalina Stops a Gem

### ISSUE THREAD

**Issue by JerTeske** [aliuosio/mage2.docker#27]
**Describe the bug**
install stops at gem install docker-sync.

**To Reproduce**
Brand new install of docker on macOS Catalina 

**Expected behavior**

**Screenshots**
gem install docker-sync;
ERROR:  While executing gem ... (URI::InvalidURIError)
    URI must be ascii only "?gems=docker-sync\u00CC"

**Desktop (please complete the following information):**
 - OS: macOS Catalina

**Comment by aliuosio** [comment]
@JerTeske 
Something is wrong with ruby.
I can't reproduce the Issue
