### ISSUE TITLE
Why my static files all 404 error?

### ISSUE THREAD

**Issue by artree-story** [aliuosio/mage2.docker#30]
I think its the ngnix config not correct. But I am not sure how can I sovle it.
system: ubuntu

**Comment by aliuosio** [comment]
@artree-story 
get the latest sources and run `install.sh` again.
i fixed that bug i think.
please keep me posted.

**Comment by artree-story** [comment]
Okay, Thanks. 
I will try, can I give an advice? I think the url is hard write, even I change in the install.sh, the nginx config is also mage2.localhost.

**Comment by aliuosio** [comment]
@artree-story 
i don't think so.
i justed search through the whole project.
You have to lets the installer run through.

**Comment by aliuosio** [comment]
@artree-story 
found it to...
looking it up

**Comment by artree-story** [comment]
Okay, I will try it.

**Comment by artree-story** [comment]
Now it's ok, but the certificate is self-signed, I move my certificate file to the /etc/letsencrypt/live/xxx folder, it seems not load.

**Comment by artree-story** [comment]
Now it's ok, good job. 
the certificate files is self-signed, I think you can add the certificate files in a folder for production environment, maybe it's better, I changed for my website. And others I want add the varnish for the magento2, I think it's fast.

**Comment by aliuosio** [comment]
i am working on a hotfix.
The Varnish Container would be great if you figure it out please commit to your fork and send me a pull request. An varnish container is beside cert registration with letsencrypt one of the "nice to have" things

**Comment by aliuosio** [comment]
@artree-story 
try again and send me a feedback please.
Merged Hotfix into master and develop.
get the newest sources. Watch Tower will pull the latest php and nginx container automatically

**Comment by artree-story** [comment]
I am not very familiar with how to pull a develop request. I will try it later.

**Comment by aliuosio** [comment]
@artree-story 
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork
