### ISSUE TITLE
OSX issues with install.sh file

### ISSUE THREAD

**Issue by CoreyWycliffe** [aliuosio/mage2.docker#31]
I'm getting errors when trying to use the install script on my Mac OSX. I don't run the script under root so that might be throwing errors. Sometimes when I change the script from ${1} to root that command will work, but then error somewhere else.

For example,
I had to change 

`chown -R $2:$2 $1;`
to
`chown -R $(whoami):$(groups $(whoami) | cut -d' ' -f1) $1;`

in the workDirCreate() function

I've also got certain commands like

`docker exec -it $2 composer global require hirak/prestissimo`
changed to
`docker exec -it -u root $2 composer global require hirak/prestissimo;`

and that will work as well.

**Expected behavior**
Run ./install script without error

**Desktop (please complete the following information):**
 - Mac OS 10.15.6 Catalina

**Additional context**
My first error was about illegal group name
https://stackoverflow.com/questions/15980675/chown-illegal-group-name-mac-os-x

Which I changed to `chown -R $(whoami):$(groups $(whoami) | cut -d' ' -f1) $1;` because my group is "staff" under my mac account.

It might all be fixed if I just run it under linux, but I felt this was something I should bring to everyone's attention.

**Comment by aliuosio** [comment]
@CoreyWycliffe 
first of all thank you for the feedback.

I understand the following bug and the solution:
`chown -R $2:$2 $1;`
to
`chown -R $(whoami):$(groups $(whoami) | cut -d' ' -f1) $1;`

and will change it

**Comment by aliuosio** [comment]
@CoreyWycliffe 
`docker exec -it $2 composer global require hirak/prestissimo`
changed to
`docker exec -it -u root $2 composer global require hirak/prestissimo;`

this will not throw errors but the composer package `hirak/prestissimo` will not be triggered later for faster composer package downloads.

i will test both solutions after upgrading my OSX and give a feedback.

You can also fork the repository and send me a pull request if you like :-)

**Comment by aliuosio** [comment]
fixed with version 2.1.3
