### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by NudeWeb** [aliuosio/mage2.docker#36]
**Describe the bug**
User does not appear to be passed correctly. Here are 2 examples (there may be more)
1. During install the following error occurs
docker exec -it chown -R userx:userx /home/userx;
----------------------------------------------------------
docker exec -it -u userx mage_php_7.4 composer global require hirak/prestissimo;
-----------------------------------------------------------------------------------
Changed current directory to /home/osio/.composer
  [ErrorException]                                                              
  file_put_contents(./composer.json): failed to open stream: Permission denied  
 
I created a work around of this by commenting out the following line in install.sh
  docker exec -it -u "$1" "$2" composer global require hirak/prestissimo                                                                             

2. After installation completed on a remote linux server, there was an nginx 404 error. 
After inspecting /etc/nginx/conf.d/default.conf
set $MAGE_ROOT /home/osio/html;
presumably it should be 
set $MAGE_ROOT /home/userx/html;

**To Reproduce**
run install.sh

**Expected behavior**
as detailed above 

Server running Ubuntu 20.04 LTS

**Comment by NudeWeb** [comment]
Bump. Just wondering if there's any feedback on this?

**Comment by aliuosio** [comment]
please clean up your docker with `docker-compose down -v` and try again.
Get the latest version of the Repro. I think i fixed it.
Please give me a feedback on this topic.

**Comment by aliuosio** [comment]
command chown has been removed
