### ISSUE TITLE
er CONNECTION_REFUSED error

### ISSUE THREAD

**Issue by hozansahin** [aliuosio/mage2.docker#40]
Hello, 
I use this docker project, but i have some problems.
in the .env file SHOPURI= I replaced with my website address, but it constantly resolves to http://localhost
My website: http://system.oyuncustore.com.tr
IP: 185.244.30.88
where could i go wrong
 I request your help in this matter.

my mother tongue is turkish so i don't know much english, sorry if i didn't explain well

**Comment by aliuosio** [comment]
For fresh install use 'bin/install.sh config' to set shop-uri.
Empty Magento Shop folder before that.

On a running system change uri in the nginx config on your host situated in the .docker folder.
Then restart with 'bin/start.sh'

**Comment by hozansahin** [comment]
> For fresh install use 'bin/install.sh config' to set shop-uri. Empty Magento Shop folder before that.
> 
> On a running system change uri in the nginx config on your host situated in the .docker folder. Then restart with 'bin/start.sh'

Hello, 
 'bin/install.sh config' When I use this command, shop-uri doesn't show a field that I can set,
Could you give some more detailed information, this is my first time installing this guide and Magento.


![image](https://user-images.githubusercontent.com/49832795/203081520-11593cd9-5676-493b-948f-1eec86f01363.png)

**Comment by aliuosio** [comment]
Ok, will make fix and inform you 😊

**Comment by aliuosio** [comment]
@hozansahin:
added Shop URL prompt to `bin/install.sh config`.
But you seem to have worked it out as i see when calling the given URL from the issue.
If you use the prompt type in `system.oyuncustore.com.tr` not `http://system.oyuncustore.com.tr/`

Please give me a feedback so i can close the issue and star the project if you have not done so yet.
