### ISSUE TITLE
Varnish not working

### ISSUE THREAD

**Issue by dellg5** [aliuosio/mage2.docker#41]
Hello, 

Thank you for you'r work, it working fine with Magento 2.4.6-p2.
So, i need to work with Varnish with this project.

After several tests on my side, the Varnish container is running well and listening to port 0.0.0.0:80->80/tcp, :::80->80/tcp, 8443/tcp, I have set up the VLC with the container information and moved the health_check file to the root. This doesn't work, I can't figure it out.
Here's the only thing I can visualize with varnishlog.

varnishlog -g raw -i Backend_health
Backend_health - default Still sick -------- 0 5 10 0.000000 0.000000 "Open error 111 (Connection refused)"

backend default {
    .host = "magento246_nginx";
    .port = "8080";
    .first_byte_timeout = 600s;
    .probe = {
        .url = "/health_check.php";
        .timeout = 2s;
        .interval = 5s;
        .window = 10;
        .threshold = 5;
   }
}

acl purge {
    "127.0.0.1";
    "magento246_nginx";
}

Can you please help me?

**Comment by aliuosio** [comment]
have you adjusted the nginx config?
at the moment it only responds on port 443 and redirects from port 80 to 443.
The current composition was not configured for varnish.

**Comment by dellg5** [comment]
Hello aliuosio,

No, i don't adjusted it, do you have some exemples for do it please ? i'm not good at :/
I just add server listen 80 and add 301 but it doesn't work, can you help me pls ? 

server {
       listen         80;
       listen    [::]:80;
       server_name magento-246;
       return         301 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    ssl_certificate      /etc/nginx/ssl/cert.crt;
    ssl_certificate_key  /etc/nginx/ssl/cert_key.key;
    ssl_ciphers          HIGH:!aNULL:!MD5;

    server_name magento-246;

    set $MAGE_ROOT /var/www/html;
    root $MAGE_ROOT/pub;

    index index.html index.php;
    autoindex off;
    charset UTF-8;
    set $MAGE_DEBUG_SHOW_ARGS 0;
    error_page 404 403 = /errors/404.php;
    add_header "X-UA-Compatible" "IE=Edge";

**Comment by aliuosio** [comment]
`
  upstream fastcgi_backend {
      server php:9000;
  }
  
  server {
      listen 80;
      listen [::]:80;
  
      server_name localhost;
  
      set $MAGE_ROOT /var/www/html;
      root $MAGE_ROOT/pub;
  
      index index.php;
      autoindex off;
      charset UTF-8;
      set $MAGE_DEBUG_SHOW_ARGS 0;
      error_page 404 403 = /errors/404.php;
      add_header "X-UA-Compatible" "IE=Edge";
  
  
      location ~* ^/setup($|/) {
          root $MAGE_ROOT;
          location ~ ^/setup/index.php {
              fastcgi_pass   fastcgi_backend;
  
              fastcgi_param  PHP_FLAG  "session.auto_start=on \n suhosin.session.cryptua=off";
              fastcgi_param  PHP_VALUE "memory_limit=3072M \n max_execution_time=1800";
              fastcgi_read_timeout 1800s;
              fastcgi_connect_timeout 1800s;
  
              fastcgi_index  index.php;
              fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
              include        fastcgi_params;
          }
  
          location ~ ^/setup/(?!pub/). {
              deny all;
          }
  
          location ~ ^/setup/pub/ {
              add_header X-Frame-Options "SAMEORIGIN";
          }
      }
  
  
      location ~* ^/update($|/) {
          root $MAGE_ROOT;
  
          location ~ ^/update/index.php {
              fastcgi_split_path_info ^(/update/index.php)(/.+)$;
              fastcgi_pass   fastcgi_backend;
              fastcgi_index  index.php;
              fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
              fastcgi_param  PATH_INFO        $fastcgi_path_info;
              include        fastcgi_params;
          }
  
          location ~ ^/update/(?!pub/). {
              deny all;
          }
  
          location ~ ^/update/pub/ {
              add_header X-Frame-Options "SAMEORIGIN";
          }
      }
  
      location / {
          try_files $uri $uri/ /index.php$is_args$args;
      }
  
      location /logs {
         alias $MAGE_ROOT/var/log;
         default_type    text/plain;
         autoindex on;
      }
  
      location /pub/ {
          location ~ ^/pub/media/(downloadable|customer|import|theme_customization/.*\.xml) {
              deny all;
          }
          alias $MAGE_ROOT/pub/;
          add_header X-Frame-Options "SAMEORIGIN";
      }
  
      location /static/ {
          location ~ ^/static/version {
              rewrite ^/static/(version[^/]+/)?(.*)$ /static/$2 last;
          }
  
          location ~* \.(ico|jpg|jpeg|png|gif|svg|js|css|swf|eot|ttf|otf|woff|woff2|json)$ {
              add_header Cache-Control "public";
              add_header X-Frame-Options "SAMEORIGIN";
              expires +1y;
  
              if (!-f $request_filename) {
                  rewrite ^/static/?(.*)$ /static.php?resource=$1 last;
              }
          }
          location ~* \.(zip|gz|gzip|bz2|csv|xml)$ {
              add_header Cache-Control "no-store";
              add_header X-Frame-Options "SAMEORIGIN";
              expires    off;
  
              if (!-f $request_filename) {
                 rewrite ^/static/?(.*)$ /static.php?resource=$1 last;
              }
          }
          if (!-f $request_filename) {
              rewrite ^/static/?(.*)$ /static.php?resource=$1 last;
          }
          add_header X-Frame-Options "SAMEORIGIN";
      }
  
      location /media/ {
          try_files $uri $uri/ /get.php$is_args$args;
  
          location ~ ^/media/theme_customization/.*\.xml {
              deny all;
          }
  
          location ~* \.(ico|jpg|jpeg|png|gif|svg|js|css|swf|eot|ttf|otf|woff|woff2)$ {
              add_header Cache-Control "public";
              add_header X-Frame-Options "SAMEORIGIN";
              expires +1y;
              try_files $uri $uri/ /get.php$is_args$args;
          }
          location ~* \.(zip|gz|gzip|bz2|csv|xml)$ {
              add_header Cache-Control "no-store";
              add_header X-Frame-Options "SAMEORIGIN";
              expires    off;
              try_files $uri $uri/ /get.php$is_args$args;
          }
          add_header X-Frame-Options "SAMEORIGIN";
      }
  
      location /media/customer/ {
          deny all;
      }
  
      location /media/downloadable/ {
          deny all;
      }
  
      location /media/import/ {
          deny all;
      }
  
      location ~ (index|get|static|report|404|503|health_check)\.php$ {
          try_files $uri =404;
          fastcgi_pass   fastcgi_backend;
          fastcgi_buffers 16 16k;
          fastcgi_buffer_size 32k;
  
          fastcgi_param  PHP_FLAG  "session.auto_start=on \n suhosin.session.cryptua=off";
          fastcgi_param  PHP_VALUE "memory_limit=3072M \n max_execution_time=1800";
          fastcgi_read_timeout 1800s;
          fastcgi_connect_timeout 1800s;
  
          fastcgi_index  index.php;
          fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
          include        fastcgi_params;
      }
  
      gzip on;
      gzip_disable "msie6";
  
      gzip_comp_level 6;
      gzip_min_length 1100;
      gzip_buffers 16 8k;
      gzip_proxied any;
      gzip_vary on;
      gzip_types
          application/atom+xml
          application/javascript
          application/json
          application/ld+json
          application/manifest+json
          application/rss+xml
          application/vnd.geo+json
          application/vnd.ms-fontobject
          application/x-font-ttf
          application/x-web-app-manifest+json
          application/xhtml+xml
          application/xml
          font/opentype
          image/bmp
          image/svg+xml
          image/x-icon
          text/cache-manifest
          text/css
          text/plain
          text/vcard
          text/vnd.rim.location.xloc
          text/vtt
          text/x-component
          text/x-cross-domain-policy;
  
  location ~* (\.php$|\.phtml$|\.htaccess$|\.git) {
           deny all;
       }
  }
`

**Comment by aliuosio** [comment]
in Database Table: core_config_data make sure that the 
path: web/secure/use_in_frontend  set value:0
path: web/secure/use_in_adminhtml set value 0

**Comment by dellg5** [comment]
Hello Aliusio, 

Thank you for taking the time to reply.
I'm coming back to you with the modifications you gave me, unfortunately it doesn't work in http. Varnish cron guru 503
I'm putting all the configuration I have on the project. Can you tell me what I've done wrong or misunderstood? 

Thanks for your work and your precious help.

Version of varnish in my projet is the same with you
>    NGINX_VERSION=1.18-alpine
>    VARNISH_VERSION=7.0.3-alpine

The default.vcl file is identical to the one in the project, I've just added this in the file, my container name for the backend and purge.

> backend default {
    .host = "magento-246_nginx";
    .port = "8080";
    .first_byte_timeout = 600s;
    .between_bytes_timeout = 300s;
    .probe = {
        .url = "/health_check.php";
        .timeout = 2s;
        .interval = 5s;
        .window = 10;
        .threshold = 5;
   }
}

> acl purge {
    "magento-246_nginx";
}

My docker-compose with varnish

>   varnish:
    container_name: ${NAMESPACE}_varnish
    image: varnish:${VARNISH_VERSION}
    environment:
      - TZ=${TZ}
      - VARNISH_SIZE=1G
    tmpfs:
      - /var/lib/varnish:exec
    command: "-p default_keep=300"
    depends_on:
      - nginx
    ports:
      - "80:80"
    volumes:
      - .docker/varnish/config/default.vcl:/etc/varnish/default.vcl
      - .docker/varnish/synth.html:/etc/varnish/synth.html

With nginx

>   nginx:
    container_name: ${NAMESPACE}_nginx
    image: nginx:${NGINX_VERSION}
    depends_on:
      - php
    ports:
      - "8080:8080"
      - "443:443"
    environment:
      SHOPURI: ${SHOPURI}
      TZ: ${TZ}
    command: '/usr/sbin/nginx -g "daemon off; error_log /dev/stderr info;"'
    networks:
      default:
        aliases:
          - ${SHOPURI}
    volumes:
      - app_data:${WORKDIR_SERVER}:delegated
      - .docker/nginx/ssl:/etc/nginx/ssl:ro
      - .docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - .docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf:ro

Nginx config > default with you'r recommandation

`## Example configuration:
upstream fastcgi_backend {
    # server  unix:/var/run/php/fpm.sock;
    server php:9000;
}

server {
    listen 80;
    listen [::]:80;
     server_name localhost;

      set $MAGE_ROOT /var/www/html;
      root $MAGE_ROOT/pub;

      index index.php;
      autoindex off;
      charset UTF-8;
      set $MAGE_DEBUG_SHOW_ARGS 0;
      error_page 404 403 = /errors/404.php;
      add_header "X-UA-Compatible" "IE=Edge";

      location ~* ^/setup($|/) {
          root $MAGE_ROOT;
          location ~ ^/setup/index.php {
              fastcgi_pass   fastcgi_backend;

              fastcgi_param  PHP_FLAG  "session.auto_start=on \n suhosin.session.cryptua=off";
              fastcgi_param  PHP_VALUE "memory_limit=3072M \n max_execution_time=1800";
              fastcgi_read_timeout 1800s;
              fastcgi_connect_timeout 1800s;

              fastcgi_index  index.php;
              fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
              include        fastcgi_params;
          }

          location ~ ^/setup/(?!pub/). {
              deny all;
          }

          location ~ ^/setup/pub/ {
              add_header X-Frame-Options "SAMEORIGIN";
          }
      }


      location ~* ^/update($|/) {
          root $MAGE_ROOT;

          location ~ ^/update/index.php {
              fastcgi_split_path_info ^(/update/index.php)(/.+)$;
              fastcgi_pass   fastcgi_backend;
              fastcgi_index  index.php;
              fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
              fastcgi_param  PATH_INFO        $fastcgi_path_info;
              include        fastcgi_params;
          }

          location ~ ^/update/(?!pub/). {
              deny all;
          }

          location ~ ^/update/pub/ {
              add_header X-Frame-Options "SAMEORIGIN";
          }
      }

      location / {
          try_files $uri $uri/ /index.php$is_args$args;
      }

      location /logs {
         alias $MAGE_ROOT/var/log;
         default_type    text/plain;
         autoindex on;
      }

      location /pub/ {
          location ~ ^/pub/media/(downloadable|customer|import|theme_customization/.*\.xml) {
              deny all;
          }
          alias $MAGE_ROOT/pub/;
          add_header X-Frame-Options "SAMEORIGIN";
      }

      location /static/ {
          location ~ ^/static/version {
              rewrite ^/static/(version[^/]+/)?(.*)$ /static/$2 last;
          }

          location ~* \.(ico|jpg|jpeg|png|gif|svg|js|css|swf|eot|ttf|otf|woff|woff2|json)$ {
              add_header Cache-Control "public";
              add_header X-Frame-Options "SAMEORIGIN";
              expires +1y;

              if (!-f $request_filename) {
                  rewrite ^/static/?(.*)$ /static.php?resource=$1 last;
              }
          }
          location ~* \.(zip|gz|gzip|bz2|csv|xml)$ {
              add_header Cache-Control "no-store";
              add_header X-Frame-Options "SAMEORIGIN";
              expires    off;

              if (!-f $request_filename) {
                 rewrite ^/static/?(.*)$ /static.php?resource=$1 last;
              }
          }
          if (!-f $request_filename) {
              rewrite ^/static/?(.*)$ /static.php?resource=$1 last;
          }
          add_header X-Frame-Options "SAMEORIGIN";
      }

      location /media/ {
          try_files $uri $uri/ /get.php$is_args$args;

          location ~ ^/media/theme_customization/.*\.xml {
              deny all;
          }

          location ~* \.(ico|jpg|jpeg|png|gif|svg|js|css|swf|eot|ttf|otf|woff|woff2)$ {
              add_header Cache-Control "public";
              add_header X-Frame-Options "SAMEORIGIN";
              expires +1y;
              try_files $uri $uri/ /get.php$is_args$args;
          }
          location ~* \.(zip|gz|gzip|bz2|csv|xml)$ {
              add_header Cache-Control "no-store";
              add_header X-Frame-Options "SAMEORIGIN";
              expires    off;
              try_files $uri $uri/ /get.php$is_args$args;
          }
          add_header X-Frame-Options "SAMEORIGIN";
      }

      location /media/customer/ {
          deny all;
      }

      location /media/downloadable/ {
          deny all;
      }

      location /media/import/ {
          deny all;
      }

      location ~ (index|get|static|report|404|503|health_check)\.php$ {
          try_files $uri =404;
          fastcgi_pass   fastcgi_backend;
          fastcgi_buffers 16 16k;
          fastcgi_buffer_size 32k;

          fastcgi_param  PHP_FLAG  "session.auto_start=on \n suhosin.session.cryptua=off";
          fastcgi_param  PHP_VALUE "memory_limit=3072M \n max_execution_time=1800";
          fastcgi_read_timeout 1800s;
          fastcgi_connect_timeout 1800s;

          fastcgi_index  index.php;
          fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
          include        fastcgi_params;
      }

      gzip on;
      gzip_disable "msie6";

      gzip_comp_level 6;
      gzip_min_length 1100;
      gzip_buffers 16 8k;
      gzip_proxied any;
      gzip_vary on;
      gzip_types
          application/atom+xml
          application/javascript
          application/json
          application/ld+json
          application/manifest+json
          application/rss+xml
          application/vnd.geo+json
          application/vnd.ms-fontobject
          application/x-font-ttf
          application/x-web-app-manifest+json
          application/xhtml+xml
          application/xml
          font/opentype
          image/bmp
          image/svg+xml
          image/x-icon
          text/cache-manifest
          text/css
          text/plain
          text/vcard
          text/vnd.rim.location.xloc
          text/vtt
          text/x-component
          text/x-cross-domain-policy;

    location ~* (.php$|.phtml$|.htaccess$|.git) {
    deny all;
  }
}`


The file health_check.php is in root projet

![Capture d’écran du 2023-09-01 09-32-40](https://github.com/aliuosio/mage2.docker/assets/60648111/f822829e-4e13-4cd0-afde-9e1ade4ef1ae)

I also change  in Database Table: core_config_data
![Capture d’écran du 2023-09-01 09-37-34](https://github.com/aliuosio/mage2.docker/assets/60648111/c102f3a6-9747-4e10-af80-e046a868b7f3)

Varnish conf in magento
![Capture d’écran du 2023-09-01 09-38-25](https://github.com/aliuosio/mage2.docker/assets/60648111/5bbe1969-bbb4-4f54-9e9c-41d6ed039da0)

Docker ps in projet
![Capture d’écran du 2023-09-01 09-44-06](https://github.com/aliuosio/mage2.docker/assets/60648111/6f6ddf2f-a8ac-4003-b037-e0e61f1db7ef)

Varnish log in container
![Capture d’écran du 2023-09-01 10-24-09](https://github.com/aliuosio/mage2.docker/assets/60648111/1f6745f9-9bc7-4e1f-91a7-81f628ec3f81)

with varnishlog -g raw -i Backend_health
![Capture d’écran du 2023-09-01 10-55-44](https://github.com/aliuosio/mage2.docker/assets/60648111/ad5a669f-9f96-4cb3-88f1-acf512452d52)

I don't understand with this not work, can you help please ?

**Comment by aliuosio** [comment]
I don't understand varnish much.
But is nginx running as standalone?
Restarted die containers?

**Comment by dellg5** [comment]
Aliusio,

I managed to make it work despite hair loss^^
you need to retrieve the latest vlc version 6 file from magento and add it to the configuration, otherwise it won't work.

> backend default {
    .host = "magento-246_nginx";
    .port = "8080";
    .first_byte_timeout = 600s;
    .probe = {
        #.url = "/health_check.php";
        .request =
            "GET /health_check.php HTTP/1.1"
            "Host: mydomaine-246.local"
            "Connection: close";
        .timeout = 2s;
        .interval = 5s;
        .window = 10;
        .threshold = 5;
    }
}

> acl purge {
    "magento-246_nginx";
}

i also add in nginx conf

>     listen 8080;
>     listen [::]:8080;

If you don't have .request params, this not work and if you test "curl -I mydomaine-246.local:8080/health_check.php" = HTTP/1.1 404 Not Found

**Comment by aliuosio** [comment]
Would you like to Le to fork my repo and commit that?
😁
