### ISSUE TITLE
Error install and add multiple websites 

### ISSUE THREAD

**Issue by ghost** [aliuosio/mage2.docker#42]
Hello Aliuosio,

Thanks in advance for your work on the Docker - Magento 2 stack.

I have a few questions though. How can I add a second site via the same project using the conf that you provide via the .env file and nginx? 

```
One site: SHOPURI=magento1.local
Two site: SHOPURI 2 ? =magento2.local
```

During installation, being on Ubuntu I also have a problem with compose. I didn't touch anything in the conf except the .env file where I set 
```
SHOPURI =magento1.local
COMPOSE_PROJECT_NAME and NAMESPACE to : magento-246
```

`file_put_contents(/home/www-data/.composer/auth.json): Failed to open stream: Permission denied
`
I'm a bit stuck on the project I'm working on, can you help me with the various topics, 
Regards,

**Comment by aliuosio** [comment]
Will look the topic up in morning and give you a solution till the evening.

**Comment by aliuosio** [comment]
Problem 1: 
you can use the docker stack different projects but you can not run them in parallel. You would have to extend the stack with traefik or nginx proxy dockers.

Problem 2:
You have to set the ownership of the .composer folder using the sudo command on the host system for the path you named.
I looked it up.
The.composer folder on the host is already set with the right permissionS. I think you jumped over the sudo message asking for you root password or you are not set in sudoers with your user.
