### ISSUE TITLE
Production deployment

### ISSUE THREAD

**Issue by raghukovvuru** [aliuosio/mage2.docker#6]
Hi.. We would like to use this repo for production with Traefik as reverse proxy and additional resources like Rabbitmq. As per your assessment is this suitable for production deployments ? 
Our plan is to test in local environment and then standalone vps with docker.

**Comment by aliuosio** [comment]
I see no problem working with it on a production server.
You should make sure that you have a configured firewall.
There are Tutorials showing you how to secure an application using docker.
If your site has heavy traffic try using docker swarm or kibernetes. 
So additional containers can spin up using scalling.
Feel free to contribute using a fork of this Repro if you have some enhancements or Bugfixs
