### ISSUE TITLE
Bug - Missing sync_userid in docker-sync.yml

### ISSUE THREAD

**Issue by rakibabu** [aliuosio/mage2.docker#9]
**Describe the bug**
First of all, I was not aware of the docker sync, so maybe this nice to append in the readme.

When installing `./install.sh` the setup fails due an error writing the vendor dir. This causes to exit the setup and not installing any vendor packages. I researched the docs of docker-sync and came found the sync_userid and sync_groupid id params. When I set the params to 1000 like this:

```
sync_userid: 1000
sync_groupid: 1000
```

The error disappeared.

**To Reproduce**
1. Follow the docs for installation
2. When installing, the setup fails on installing composer packages.

**Expected behavior**
No errors on install.

**Desktop (please complete the following information):**
 - OS: Mac OS  
 - Version Mojave 10.14.6

**Comment by aliuosio** [comment]
will look at it under OSX

**Comment by rakibabu** [comment]
Can make a PR for this to if you want

**Comment by aliuosio** [comment]
nice, welcome aboard

**Comment by aliuosio** [comment]
@rakibabu 
chapeau
